from airflow import DAG
from airflow.operators.python_operator import PythonOperator

from datetime import datetime, timedelta  
import datetime as dt
from dateutil import tz
import praw
import pymongo
import time

USERNAME = 'Still_Statistician32'
PASSticker = 'BD99cjOO'
CLIENT_ID = 'CSwmabTf7mzgHTmg2zynPg'
SECRET_TOKEN = '9VSTmChi6sqT5JCct1ha8Y3ctxKeVg'

tickers_dict={
    'singapore airlines': 'Singapore Airlines Limited',
    'dbs': 'DBS Group Holdings Ltd',
    'comfortdelgro': 'ComfortDelGro Corporation Limited',
    'genting': 'Genting Singapore Limited',
    'capitaland': 'CapitaLand Integrated Commercial Trust',
    'uob': 'United Overseas Bank Limited',
    'mapletree logistics': 'Mapletree Logistics Trust',
    'mapletree commercial': 'Mapletree Commercial Trust',
    'sats': 'SATS Ltd',
    'wilmar': 'Wilmar International Limited',
    'singtel': 'Singapore Telecommunications Limited',
    'city dev': 'City Developments Limited',
    'yangzijiang shipbuilding': 'Yangzijiang Shipbuilding (Holdings) Ltd',
    'thai beverage public company': 'Thai Beverage Public Company Limited',
    'venture corporation': 'Venture Corporation Limited',
    'sembcorp': 'Sembcorp Industries Ltd',
    'ascendas': 'Ascendas Real Estate Investment Trust',
    'frasers': 'Frasers Logistics & Commercial Trust',
    'hongkong land holdings': 'Hongkong Land Holdings Limited',
    'st engineering': 'Singapore Technologies Engineering Ltd'
}

def get_reddit_data():
    reddit = praw.Reddit(client_id=CLIENT_ID, 
                     client_secret=SECRET_TOKEN,
                     passticker=PASSticker, 
                     user_agent='TESTING praw accessAPI:v0.0.1 (by /u/Still_Statistician32)',
                     username=USERNAME)
    subreddit = reddit.subreddit('singapore')
    sgx_list = []
    start = time.time()
    for word in tickers_dict.keys():
        sgx_subreddit = subreddit.search(word)
        from_zone = tz.gettz('UTC')
        to_zone = tz.gettz('Singapore')
        for posts in sgx_subreddit:
            sgx_dict = {}
            # Convert UTC to GMT+8
            new_datetime = str(dt.datetime.fromtimestamp(posts.created))
            utc = datetime.strptime(new_datetime, '%Y-%m-%d %H:%M:%S')
            utc = utc.replace(tzinfo=from_zone)
            local = utc.astimezone(to_zone)
            local_dt = local.strftime('%Y-%m-%d %H:%M:%S')
            
            if (local_dt == (datetime.today() - timedelta(days=1)).date()):
                sgx_dict['datetime_created'] = local_dt
                sgx_dict['source'] = 'Reddit'
                ticker_list = []
                for ticker, name in tickers_dict.items():
                    if (ticker in posts.selftext.lower()) or (ticker in posts.title.lower()):
                        ticker_list.append(name)
                sgx_dict['ticker'] = ticker_list
                sgx_dict['publisher'] = str(posts.author)
                sgx_dict['text'] = posts.selftext
                sgx_dict['title'] = posts.title
                sgx_dict['score'] = posts.score
                sgx_dict['url'] = posts.url
                sgx_list.append(sgx_dict)
    end = time.time()
    print('Time execution duration (secs): ', end-start)
    
    # if API does not work, use mock data instead.
    # sgx_list = [{'datetime_created': '2022-02-14 07:49:34',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'skyscraper56',
    # 'text': '',
    # 'title': 'Passengers can look forward to new cabin features when Singapore Airlines takes delivery of new fleet',
    # 'score': 39,
    # 'url': 'https://str.sg/wW6w'},
    # {'datetime_created': '2022-03-20 06:06:32',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'AsgardianGoat',
    # 'text': "I called Singapore Airlines US number and I was on hold for 4 hours and 30 minutes, I finally hung up. I then tried their online chat service, which after waiting for about an hour disconnected me, not once, but twice, saying that agents are not available. There is no way I can reach these guys. I am afraid to purchase a ticket from them because if I need to make a change I won't be able to change the ticket. I know they have online self service, but not everything can be done online.",
    # 'title': 'Singapore Airlines Customer Service Hold Times',
    # 'score': 9,
    # 'url': 'https://www.reddit.com/r/singapore/comments/ti65fp/singapore_airlines_customer_service_hold_times/'},
    # {'datetime_created': '2022-02-24 18:35:51',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MicrotechAnalysis',
    # 'text': '',
    # 'title': 'Singapore Airlines posts first quarterly profit since start of pandemic',
    # 'score': 87,
    # 'url': 'https://www.todayonline.com/world/singapore-airlines-posts-first-quarterly-profit-start-pandemic-1825941'},
    # {'datetime_created': '2022-02-01 07:03:36',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'PhebeSandifer',
    # 'text': '',
    # 'title': 'Singapore Airlines To Start Operating Daily Flights to Bali on February 16',
    # 'score': 198,
    # 'url': 'https://www.travelinglifestyle.net/singapore-airlines-to-start-operating-daily-flights-to-bali-on-february-16/'},
    # {'datetime_created': '2021-12-08 09:46:10',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'misty1497',
    # 'text': '',
    # 'title': 'Has anyone been able to get ahold of Singapore Airlines? I’ve been on hold for a ridiculous amount of time and don’t know if I’ll ever speak to someone.',
    # 'score': 458,
    # 'url': 'https://i.redd.it/7r7a0yuq48481.jpg'},
    # {'datetime_created': '2022-02-03 12:41:02',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MicrotechAnalysis',
    # 'text': '',
    # 'title': "Singapore Airlines ranked top global airline, leading Asian firm in Fortune's top 50 list",
    # 'score': 47,
    # 'url': 'https://www.straitstimes.com/singapore/transport/singapore-airlines-ranked-top-global-airline-leading-asian-firm-in-fortunes-top-50-list'},
    # {'datetime_created': '2021-12-02 14:32:34',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'P838',
    # 'text': '',
    # 'title': 'The wait time at Singapore Airlines customer service office @ ION Orchard ~ 4 hour wait',
    # 'score': 242,
    # 'url': 'https://i.redd.it/o63tl6qeq2381.jpg'},
    # {'datetime_created': '2022-01-13 15:07:54',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MicrotechAnalysis',
    # 'text': '',
    # 'title': 'Singapore Airlines raises US$600 million in US dollar bond deal',
    # 'score': 32,
    # 'url': 'https://www.todayonline.com/world/singapore-airlines-raises-us600-million-us-dollar-bond-deal-1789691'},
    # {'datetime_created': '2021-11-20 23:50:33',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MicrotechAnalysis',
    # 'text': '',
    # 'title': 'Singapore Airlines unveiled a swanky new lie-flat business class seat on its Boeing 737 MAX plane',
    # 'score': 58,
    # 'url': 'https://www.businessinsider.com/photos-new-singapore-airlines-narrowbody-lie-flat-business-class-seat-2021-11'},
    # {'datetime_created': '2021-11-05 14:05:55',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MyWholeTeamsDead',
    # 'text': '',
    # 'title': 'Singapore Airlines SFO-SIN flight cancelled after plane makes contact with another aircraft on the ground',
    # 'score': 79,
    # 'url': 'https://www.channelnewsasia.com/singapore/singapore-airlines-san-francisco-flight-cancelled-sq33-2293231'},
    # {'datetime_created': '2021-10-05 10:13:52',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'haikallp',
    # 'text': '',
    # 'title': 'Two Singapore Airlines A380s towed along public road to be scrapped at Changi Exhibition Centre',
    # 'score': 126,
    # 'url': 'https://www.channelnewsasia.com/singapore/sia-a380-scrap-singapore-airlines-changi-2215261'},
    # {'datetime_created': '2021-11-12 13:55:27',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'annoyedwityou',
    # 'text': '',
    # 'title': 'Singapore Airlines has 79% of fleet ready to use on any demand increase',
    # 'score': 37,
    # 'url': 'https://sg.finance.yahoo.com/news/singapore-airlines-79-fleet-ready-032419078.html'},
    # {'datetime_created': '2021-10-11 21:35:47',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Angryangmo',
    # 'text': '',
    # 'title': 'Singapore Airlines launches seasonal flights to Vancouver, first to Canada since 2009',
    # 'score': 62,
    # 'url': 'https://www.channelnewsasia.com/business/singapore-airlines-vancouver-canada-flight-service-vtl-covid-19-vaccinated-travel-lane-2236071'},
    # {'datetime_created': '2021-10-02 09:31:50',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MyWholeTeamsDead',
    # 'text': '',
    # 'title': 'This dog flew Singapore Airlines business class from Sydney to Italy',
    # 'score': 215,
    # 'url': 'https://www.executivetraveller.com/news/this-dog-flew-singapore-airlines-business-class-from-sydney-to-italy'},
    # {'datetime_created': '2021-09-16 20:16:26',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Tiger2021J',
    # 'text': '',
    # 'title': 'Singapore Airlines uses up last S$600 million of 2020 rights issue',
    # 'score': 113,
    # 'url': 'https://www.businesstimes.com.sg/transport/singapore-airlines-uses-up-last-s600-million-of-2020-rights-issue'},
    # {'datetime_created': '2021-12-04 21:03:51',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'PrataKosong-',
    # 'text': '',
    # 'title': 'The Singapore Airlines 2021 Experience - What’s Changed Onboard?',
    # 'score': 0,
    # 'url': 'https://youtu.be/Kav6n7tTCQY'},
    # {'datetime_created': '2021-07-08 18:01:54',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'stforumtroll2',
    # 'text': '',
    # 'title': 'Cash-rich Singapore Airlines aims for regional dominance as rivals pull back',
    # 'score': 120,
    # 'url': 'https://www.todayonline.com/singapore/cash-rich-singapore-airlines-aims-regional-dominance-rivals-pull-back?cid=tdy%20tg_tg-pm_social-msging-free_09102018_today'},
    # {'datetime_created': '2021-08-04 19:52:12',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'pyonguno',
    # 'text': '',
    # 'title': 'Singapore Airlines A380 kicks up desert dust as it departs Australian storage facility',
    # 'score': 149,
    # 'url': 'https://www.traveller.com.au/singapore-airlines-a380-kicks-up-desert-dust-as-it-departs-australian-storage-facility-h1xmvs'},
    # {'datetime_created': '2021-09-07 21:16:16',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Doraemonhacker',
    # 'text': '',
    # 'title': 'Review: COVID-era service on Singapore Airlines A350-900 Business Class, Singapore to Munich.',
    # 'score': 26,
    # 'url': 'https://milelion.com/2021/09/07/review-covid-era-service-on-singapore-airlines-a350-900-business-class-singapore-to-munich/?utm_source=telegram&utm_medium=telegram&utm_campaign=roars'},
    # {'datetime_created': '2021-05-25 15:58:16',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'vaish7848',
    # 'text': '',
    # 'title': 'Singapore Airlines reroutes flights to avoid Belarus airspace after forced landing of Ryanair plane',
    # 'score': 193,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/singapore-airlines-belarus-airspace-flights-roman-protasevich-14881388'},
    # {'datetime_created': '2021-08-13 18:00:19',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'theloneranger_55',
    # 'text': '',
    # 'title': "Singapore Airlines ends MVC salary cuts for S'pore-based staff from Aug 1",
    # 'score': 11,
    # 'url': 'https://www.straitstimes.com/business/companies-markets/singapore-airlines-ends-mvc-salary-cuts-for-singapore-based-staff-from'},
    # {'datetime_created': '2021-05-31 06:22:54',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'JiPaiHongGanLiao',
    # 'text': '',
    # 'title': 'Singapore airlines updated their marketing Batik Motif, the first time since 1974. Uniforms will not be updated. (This is what you see on their cardholders, Duty free SQ stuff etc)',
    # 'score': 257,
    # 'url': 'https://www.reddit.com/gallery/nom5ef'},
    # {'datetime_created': '2021-04-28 09:17:11',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Varantain',
    # 'text': '',
    # 'title': 'Singapore Airlines adding new award category - is a KrisFlyer devaluation coming?',
    # 'score': 84,
    # 'url': 'https://mainlymiles.com/2021/04/28/singapore-airlines-adding-new-award-category-is-a-krisflyer-devaluation-coming/'},
    # {'datetime_created': '2021-10-22 23:09:44',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Happyboynumber1',
    # 'text': '',
    # 'title': 'Welcome Back Singapore Airlines!',
    # 'score': 0,
    # 'url': 'https://www.youtube.com/watch?v=_w6R_jwfTAQ'},
    # {'datetime_created': '2021-06-20 16:31:58',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'BabaDuda',
    # 'text': '',
    # 'title': 'The Runway Was Not Clear (Singapore Airlines Flight 006/SQ006)',
    # 'score': 27,
    # 'url': 'https://www.youtube.com/watch?v=8rXmskgv8nw'},
    # {'datetime_created': '2021-03-26 10:32:23',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'chintokkong',
    # 'text': '',
    # 'title': '‘SQ117 owes me a glass of fresh milk’: The Singapore Airlines hijacking, 30 years on',
    # 'score': 153,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/sq117-hijack-commando-singapore-airlines-14486940'},
    # {'datetime_created': '2021-04-02 19:04:45',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'PublicSummer0',
    # 'text': '',
    # 'title': 'Hong Kong government bars Singapore Airlines passenger flights from Apr 3 to 16',
    # 'score': 68,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/singapore-airlines-sia-hong-kong-covid-19-14545178'},
    # {'datetime_created': '2021-09-16 16:51:34',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'justmewayne',
    # 'text': '',
    # 'title': 'Singapore Airlines suspends services to Australia',
    # 'score': 0,
    # 'url': 'https://www.traveldailymedia.com/singapore-airlines-suspends-services-to-australia/'},
    # {'datetime_created': '2021-05-26 13:29:27',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'ElopeToTheMoon',
    # 'text': '',
    # 'title': "Orchard Rows: The story of Singapore Airlines' ill-fated jackpot machines | The Milelion",
    # 'score': 38,
    # 'url': 'https://milelion.com/2021/05/26/orchard-rows-the-story-of-singapore-airlines-ill-fated-jackpot-machines/?utm_source=telegram&utm_medium=telegram&utm_campaign=roars'},
    # {'datetime_created': '2021-06-06 13:15:23',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'ashskier',
    # 'text': '',
    # 'title': 'MSA: Mercury Singapore Airlines, or Malaysia Says Alamak | The Milelion',
    # 'score': 30,
    # 'url': 'https://milelion.com/2021/06/06/msa-mercury-singapore-airlines-or-malaysia-says-alamak/'},
    # {'datetime_created': '2021-03-09 15:54:02',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'djmpence',
    # 'text': '',
    # 'title': 'Latest photos of mothballed Singapore Airlines A380 jets in Alice Springs - from John Slabbert’s fb page',
    # 'score': 113,
    # 'url': 'https://i.redd.it/7ilz0kdnkyl61.jpg'},
    # {'datetime_created': '2020-09-25 10:42:16',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'l0neT',
    # 'text': '',
    # 'title': 'We must save Singapore Airlines from this existential crisis',
    # 'score': 42,
    # 'url': 'https://www.channelnewsasia.com/news/commentary/singapore-airlines-layoff-national-carrier-temasek-government-13137324'},
    # {'datetime_created': '2021-05-25 05:45:38',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'HengArIKeat2bPM',
    # 'text': '',
    # 'title': 'This MSA plane has a variant of the airline name as “Malaysia+Singapore” painted on the fuselage. It also bears the flag of the 2 countries. Other variants include “MSA” or “Malaysia-Singapore Airlines” 1970, Kai Tak. Credits to David Wilson.',
    # 'score': 34,
    # 'url': 'https://i.redd.it/ardj86pa25171.jpg'},
    # {'datetime_created': '2021-06-04 13:10:43',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'justmewayne',
    # 'text': '',
    # 'title': 'Singapore Airlines Concorde: The full story',
    # 'score': 22,
    # 'url': 'https://mainlymiles.com/2021/06/03/singapore-airlines-concorde-the-full-story/'},
    # {'datetime_created': '2021-04-25 19:44:50',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'internweb',
    # 'text': '',
    # 'title': 'Singapore Airlines restarting Bali flights in May',
    # 'score': 50,
    # 'url': 'https://mainlymiles.com/2021/04/05/singapore-airlines-restarting-bali-flights-in-may/'},
    # {'datetime_created': '2021-04-03 00:05:02',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Jammy_buttons2',
    # 'text': '',
    # 'title': "Singapore Airlines passenger flights to Hong Kong suspended after COVID-19 testing 'trigger point' breached: CAAS",
    # 'score': 30,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/singapore-airlines-flights-hong-kong-suspended-covid-19-case-14546112?cid=FBcna&fbclid=IwAR2wjGUCvCodmtyJqvKlIBEcNL-IhHbREdzTbKkI_HhEPZQ-oPIU8PB1Ck4'},
    # {'datetime_created': '2020-11-07 10:44:26',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Jammy_buttons2',
    # 'text': '',
    # 'title': 'Singapore Airlines to retire 7 A380s, 19 other aircraft following S$3.5 billion loss',
    # 'score': 90,
    # 'url': 'https://mainlymiles.com/2020/11/06/singapore-airlines-to-retire-7-a380s-21-other-aircraft-following-s3-5-billion-loss/?fbclid=IwAR0PxnnKQgKnWmVOZwBzGuNtgGsjZItqOG-RvC9avkMBTwUi1pwGLmz7k3o'},
    # {'datetime_created': '2020-04-30 14:51:40',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'dingo_mango',
    # 'text': '',
    # 'title': 'Recreated the Singapore Airlines uniform in Animal Crossing',
    # 'score': 2079,
    # 'url': 'https://i.redd.it/e0n6fao7kwv41.jpg'},
    # {'datetime_created': '2021-01-12 23:19:58',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Durian881',
    # 'text': '',
    # 'title': 'Eligible Singapore Airlines staff members to get COVID-19 vaccine from Jan 13',
    # 'score': 57,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/covid-19-singapore-airlines-sia-staff-vaccine-jan-13-aviation-13945272'},
    # {'datetime_created': '2020-09-09 08:48:16',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Foxie13x',
    # 'text': '',
    # 'title': 'Rumour: "Flycations" to nowhere on Singapore Airlines coming soon?',
    # 'score': 46,
    # 'url': 'https://milelion.com/2020/09/09/rumour-flycations-to-nowhere-on-singapore-airlines-coming-soon/'},
    # {'datetime_created': '2021-02-09 17:15:31',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'PublicSummer0',
    # 'text': '',
    # 'title': 'Singapore Airlines cabin crew member on turnaround flight among 11 new imported COVID-19 cases in Singapore: MOH',
    # 'score': 26,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/covid-19-new-cases-singapore-airlines-cabin-crew-member-sia-14143714'},
    # {'datetime_created': '2020-11-11 16:56:51',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'vaish7848',
    # 'text': '',
    # 'title': 'A passenger demonstrates one the features of a first-class compartment on-board a Singapore Airlines 747 (1975)',
    # 'score': 166,
    # 'url': 'https://i.redd.it/af5lmze9sky51.jpg'},
    # {'datetime_created': '2020-04-09 00:30:34',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'weird_flex_buto_k',
    # 'text': '',
    # 'title': 'Singapore Airlines flight bringing in masks to Singapore :)',
    # 'score': 564,
    # 'url': 'https://i.redd.it/fs90w5sffmr41.jpg'},
    # {'datetime_created': '2020-05-15 11:24:40',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'djmpence',
    # 'text': '',
    # 'title': 'Alaska Wants Singapore Airlines To Start Passenger Flights And Potentially Open A Hub In Anchorage During COVID-19',
    # 'score': 150,
    # 'url': 'https://www.forbes.com/sites/willhorton1/2020/05/13/alaska-wants-singapore-airlines-to-start-passenger-flights-and-potentially-open-a-hub-in-anchorage-during-covid-19/'},
    # {'datetime_created': '2020-10-24 17:53:27',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'blissfulreveriee',
    # 'text': '',
    # 'title': 'Inaugural Singapore Airlines A-380 dining experience takes off at Changi Airport',
    # 'score': 42,
    # 'url': 'https://www.straitstimes.com/singapore/transport/inaugural-singapore-airlines-a-380-dining-experience-takes-off-at-changi-airport'},
    # {'datetime_created': '2020-07-13 06:46:44',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'vaish7848',
    # 'text': '',
    # 'title': 'Singapore Airlines receives its first Boeing 747 (Seattle, 1973)',
    # 'score': 400,
    # 'url': 'https://i.redd.it/bxtbpta59ia51.jpg'},
    # {'datetime_created': '2020-03-23 09:19:32',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Flukaku',
    # 'text': '',
    # 'title': 'COVID-19: Singapore Airlines slashes 96% of capacity, grounds most planes',
    # 'score': 122,
    # 'url': 'https://www.channelnewsasia.com/news/business/covid-19-singapore-airlines-suspend-flights-coronavirus-12566248'},
    # {'datetime_created': '2020-12-18 14:38:33',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'thestudiomaster',
    # 'text': '',
    # 'title': 'Why Singapore Airlines is boosting New York JFK, LAX, San Francisco flights to daily',
    # 'score': 40,
    # 'url': 'https://thepointsguy.com/news/singapore-airlines-daily-us-flights-2021/'},
    # {'datetime_created': '2020-08-02 06:34:29',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'vaish7848',
    # 'text': '',
    # 'title': 'Remember when Singapore Airlines actually operated a Concorde',
    # 'score': 160,
    # 'url': 'https://i.redd.it/lm57shw6xge51.jpg'},
    # {'datetime_created': '2020-10-02 17:55:20',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Twrd4321',
    # 'text': '',
    # 'title': 'Singapore Airlines eliminates printed menus in digital drive to reduce waste',
    # 'score': 42,
    # 'url': 'https://mainlymiles.com/2020/10/02/singapore-airlines-eliminates-printed-menus-in-digital-drive-to-reduce-waste/'},
    # {'datetime_created': '2020-05-14 18:19:55',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'stforumtroll2',
    # 'text': '',
    # 'title': 'Singapore Airlines posts first annual net loss in 48-year history after COVID-19 cripples demand',
    # 'score': 134,
    # 'url': 'https://www.channelnewsasia.com/news/business/singapore-airlines-sia-q4-full-year-results-covid-19-coronavirus-12732134'},
    # {'datetime_created': '2020-09-16 05:17:22',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'vaish7848',
    # 'text': '',
    # 'title': 'Singapore Airlines 747-300 in the background, with a 14 ft cutaway model of it. (1984)',
    # 'score': 171,
    # 'url': 'https://i.redd.it/vmk9u8dgodn51.jpg'},
    # {'datetime_created': '2020-07-05 14:01:11',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'accuraintegra23',
    # 'text': '',
    # 'title': 'Singapore Airlines Concorde',
    # 'score': 158,
    # 'url': 'https://i.redd.it/xswfs65dbz851.jpg'},
    # {'datetime_created': '2020-11-22 17:32:47',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'justmewayne',
    # 'text': '',
    # 'title': "Hands-on: Singapore Airlines' radical new Economy Class meal concept",
    # 'score': 22,
    # 'url': 'https://milelion.com/2020/11/22/hands-on-singapore-airlines-radical-new-economy-class-meal-concept/'},
    # {'datetime_created': '2021-02-16 03:36:05',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'bengyap',
    # 'text': '',
    # 'title': 'Operation Thunderbolt: Singapore Airlines Flight 117 | March 1991',
    # 'score': 10,
    # 'url': 'https://www.youtube.com/watch?v=xnDhiH0Dmfc'},
    # {'datetime_created': '2020-03-17 06:55:01',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'plonk30',
    # 'text': "3rd attempt at calling .... Approximately 4 hours of my life that I'm never getting back",
    # 'title': "The tune that Singapore Airlines play when you're on hold is so stuck in my head that it may never leave",
    # 'score': 56,
    # 'url': 'https://www.reddit.com/r/singapore/comments/fju86d/the_tune_that_singapore_airlines_play_when_youre/'},
    # {'datetime_created': '2019-03-03 10:16:33',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'runebound2',
    # 'text': '',
    # 'title': "As a Special Forces soldier, he stormed a hijacked Singapore Airlines plane. Now he's a monk",
    # 'score': 852,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/special-forces-storm-hijack-singapore-airlines-monk-fred-cheong-11279702/'},
    # {'datetime_created': '2020-08-25 18:38:05',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'HengArIKeat2bPM',
    # 'text': '',
    # 'title': 'This 1969 route map of Malaysia Singapore Airlines (MSA) shows the bulk of international routes was from Singapore.',
    # 'score': 64,
    # 'url': 'https://i.redd.it/1jxdl9a9n4j51.jpg'},
    # {'datetime_created': '2019-12-16 08:55:51',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MyWholeTeamsDead',
    # 'text': '',
    # 'title': "Singapore Airlines' first 737 MAX 8 in full colours",
    # 'score': 70,
    # 'url': 'https://i.redd.it/u133i0oq8w441.jpg'},
    # {'datetime_created': '2019-07-14 12:34:12',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MyWholeTeamsDead',
    # 'text': '',
    # 'title': 'Singapore Airlines A380 (9V-SKN) in a bird-strike incident at Paris',
    # 'score': 309,
    # 'url': 'https://imgur.com/a/ZHkScml'},
    # {'datetime_created': '2020-10-26 10:37:54',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'bluecapella',
    # 'text': '',
    # 'title': 'S$321 business class experience onboard Singapore Airlines’ Restaurant A380',
    # 'score': 2,
    # 'url': 'https://www.todayonline.com/singapore/my-s321-business-class-experience-onboard-singapore-airlines-restaurant-a380'},
    # {'datetime_created': '2019-12-06 17:37:17',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'TanZhiYuan23',
    # 'text': '',
    # 'title': 'First regional aircraft painted in Singapore Airlines livery instead of Silk Air (Not completed painting, 737 MAX)',
    # 'score': 94,
    # 'url': 'https://i.redd.it/eihj7bthgz241.png'},
    # {'datetime_created': '2020-09-27 15:19:52',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'l0neT',
    # 'text': '',
    # 'title': 'Vistara partner Singapore Airlines concerned over Tatas’ interest in Air India',
    # 'score': 14,
    # 'url': 'https://www.timesnownews.com/business-economy/companies/article/vistara-partner-singapore-airlines-concerned-over-tatas-interest-in-air-india/658094'},
    # {'datetime_created': '2020-03-26 12:49:12',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Csyip',
    # 'text': '',
    # 'title': 'Singapore Airlines calls for trading halt pending announcement',
    # 'score': 46,
    # 'url': 'https://www.businesstimes.com.sg/companies-markets/singapore-airlines-calls-for-trading-halt-pending-announcement'},
    # {'datetime_created': '2020-10-26 22:05:58',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'stforumtroll2',
    # 'text': '',
    # 'title': 'Ghib Ojisan - Singapore Airlines (non-flying) Business Class Review | A380 Restaurant✈️',
    # 'score': 3,
    # 'url': 'https://www.youtube.com/watch?v=norXpy9fWsk'},
    # {'datetime_created': '2020-02-23 02:45:33',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'ArmedSweeping',
    # 'text': '',
    # 'title': 'After retiring the 752 in 1990, Singapore airlines (SIA / SQ) has not operated a narrow body (single aisle) aircraft for 30 years, almost half of their operating life. Following the merger with Silkair, SQ will operate a narrow body aircraft type again. A SQ B737 MAX 8 and a SQ 737 -100 compared.',
    # 'score': 62,
    # 'url': 'https://i.redd.it/urhdeo6ltii41.jpg'},
    # {'datetime_created': '2020-06-12 17:35:11',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'djmpence',
    # 'text': '',
    # 'title': 'Cancellation of the Formula 1 Singapore Airlines Singapore Grand Prix 2020',
    # 'score': 15,
    # 'url': 'https://singaporegp.sg/en/news/2020/cancellation-of-the-formula-1-singapore-airlines-singapore-grand-prix-2020'},
    # {'datetime_created': '2020-07-29 18:10:44',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'FitCranberry',
    # 'text': '',
    # 'title': 'Singapore Airlines reports $817 million loss in first quarter due to pandemic',
    # 'score': 22,
    # 'url': 'https://sg.finance.yahoo.com/news/singapore-airlines-reports-817-million-093716450.html'},
    # {'datetime_created': '2020-08-04 15:48:23',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'MyWholeTeamsDead',
    # 'text': '',
    # 'title': 'Singapore Airlines will start flying Boeing 737s in early 2021 - Executive Traveller',
    # 'score': 17,
    # 'url': 'https://www.executivetraveller.com/news/singapore-airlines-silkair-boeing-737s'},
    # {'datetime_created': '2020-08-15 16:33:37',
    # 'source': 'Reddit',
    # 'ticker': [],
    # 'publisher': 'icekacangkopi',
    # 'text': "During the start of year of the year I book a flight with SIA but unfortunely covid came. I could not cancelled on economy flight ticket but they managed to put an open ticket for a year. Looking at things now coming close to end of the year I doubt I can't fly anywhere still. \n\nI doubt refund is possible as its not a flexi ticket. I guess my only option to maybe pay for an extension of open ticket?",
    # 'title': 'Singapore airline postponed flight ticket. Anybody affected?',
    # 'score': 8,
    # 'url': 'https://www.reddit.com/r/singapore/comments/ia3vml/singapore_airline_postponed_flight_ticket_anybody/'},
    # {'datetime_created': '2020-04-03 23:34:31',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'winterdates',
    # 'text': '',
    # 'title': "COVID-19: Singapore Airlines to provide 300 'care ambassadors' to fill manpower gap at hospitals",
    # 'score': 45,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/covid-19-singapore-airlines-care-ambassadors-hospital-manpower-12608118'},
    # {'datetime_created': '2020-01-25 22:47:58',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'sweesweeswe',
    # 'text': '',
    # 'title': 'Singapore Airlines’ budget arm Scoot said on Saturday (Jan 25) that it is making arrangements for a flight to bring back Singaporean passengers as well as the crew of flight TR188 which landed in the Chinese city of Hangzhou from Singapore on Friday.',
    # 'score': 85,
    # 'url': 'https://i.redd.it/enn453aotxc41.jpg'},
    # {'datetime_created': '2020-05-16 16:07:23',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'CreativeMarzipan',
    # 'text': '',
    # 'title': 'Singapore Airlines carried only 300 passengers per day in April',
    # 'score': 41,
    # 'url': 'https://mainlymiles.com/2020/05/15/singapore-airlines-carried-only-300-passengers-per-day-in-april/'},
    # {'datetime_created': '2019-07-28 10:03:34',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'risingsuncoc',
    # 'text': '',
    # 'title': 'How airplane food is prepared for Singapore Airlines',
    # 'score': 66,
    # 'url': 'https://www.youtube.com/watch?v=1m6h59wI_yI'},
    # {'datetime_created': '2020-04-01 20:29:26',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'detectivesher',
    # 'text': '\nI hope you and your loved ones are well in these extraordinary times.\n\n\n\nFew, if any, of us could have imagined a global pandemic like this as country after country bans international travel due to a viral outbreak. While the measures to contain Covid-19 have been taken from a public health perspective, they have crippled the airline industry and presented us at Singapore Airlines with the greatest challenge in our history.\n\n\n\nOur customers and staff always remain our top-priority. That principle guided many of our decisions over the last two months as we responded to the increasingly global scale of the outbreak, as well as the growing number of border closures that have decimated air travel.\n\n\n\nWe know that you trust us to deliver a safe flying experience and ground environment. That is why we modified our in-flight service to reduce the risks to our customers and crew while in the air, and stepped up our cleaning and disinfection procedures both in the aircraft and our ground facilities such as the SilverKris lounges.\n\n\n\nEven as we scaled back our operations due to the borders closures, we understood that many of you and your loved ones needed to return home as soon as possible. And you trusted us to make that possible. That is why, despite the fast deteriorating operating economics, we persisted with services to key cities for as long as we could.\nWe have received many encouraging notes from our customers over the last few weeks. Thank you, your warm words of appreciation mean a great deal to us during this trying time.\n\n\n\nAt the same time, we also know that many of you have been adversely affected by the large-scale flight cancellations. I sincerely apologise for this.\nOur teams have received an unprecedented volume of calls, messages and emails over the last few weeks. While we ramped up the handling capacity at our customer services centres, a few of our overseas contact centre operations were disrupted by government-imposed lockdowns. As a result, we know that we might have caused you considerable frustration and anxiety. We appreciate your patience and understanding as we do everything we can to support your needs, and respond to you as soon as possible.\nIn view of the uncertainty amid the Covid-19 outbreak, the value of the unused portion of your tickets will be retained as flight credits when your flight has been cancelled or if you would like to postpone your travel. You can use those credits to make a new booking any time from now until 31 March 2021. We have also waived no-show and rebooking fees. Please contact us here when you firm up your new travel plans.\n\n\n\n\nI would also like to share that we will automatically renew all KrisFlyer Elite and PPS Club membership statuses for another 12 months at the end of their membership year. This applies to all memberships expiring from March 2020 through to February 2021. The validity of any expiring PPS and Elite Gold Rewards will also be extended until 31 March 2021.\n\n\n\nThis is a small token of our appreciation for your loyalty and support, which we value greatly as we work hard to get through this outbreak.\nFor more than 70 years, SIA has set the standard for in-flight products and services in the aviation industry. It remains unclear when the Covid-19 outbreak will be brought under control. But when it does, you can be sure that we will be ready to welcome you back on board and deliver, once again, the exceptional service that you have come to expect and are familiar with.\nUntil then, please stay safe and healthy',
    # 'title': 'Singapore Airline message from CEO',
    # 'score': 44,
    # 'url': 'https://www.reddit.com/r/singapore/comments/fsyur6/singapore_airline_message_from_ceo/'},
    # {'datetime_created': '2020-01-08 10:47:58',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'FitCranberry',
    # 'text': '',
    # 'title': 'Singapore Airlines diverts flights from Iranian airspace after attack on US-led forces in Iraq',
    # 'score': 58,
    # 'url': 'https://www.straitstimes.com/world/middle-east/singapore-airlines-diverts-flights-from-iranian-airspace-after-attack-on-us-led'},
    # {'datetime_created': '2020-07-03 09:35:41',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'djmpence',
    # 'text': '',
    # 'title': 'Singapore Airlines KrisFlyer miles expiry date extension to June 2021',
    # 'score': 18,
    # 'url': 'https://www.executivetraveller.com/news/singapore-airlines-krisflyer-miles-expiry-extension'},
    # {'datetime_created': '2018-09-02 19:43:01',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'micketymoc',
    # 'text': '',
    # 'title': 'Singapore Airlines turned down a mention in Crazy Rich Asians - SQ "not sure the movie would represent the airline and their customer in a good light"',
    # 'score': 275,
    # 'url': 'https://www.thewrap.com/crazy-rich-asians-how-mega-rich-world-was-created-for-30-million/'},
    # {'datetime_created': '2018-01-03 15:55:06',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'cowbungaa',
    # 'text': '',
    # 'title': "Singapore Airlines' move to charge credit card fees is a disgraceful money grab",
    # 'score': 206,
    # 'url': 'http://milelion.com/2018/01/03/singapore-airlines-move-charge-credit-card-fees-disgraceful-money-grab/'},
    # {'datetime_created': '2019-11-11 10:02:42',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'ongcs',
    # 'text': '',
    # 'title': 'With mergers a hard sell, Singapore Airlines embraces Malaysia deal',
    # 'score': 45,
    # 'url': 'https://www.scmp.com/week-asia/economics/article/3036669/singapore-airlines-says-malaysia-airlines-tie-best-approach'},
    # {'datetime_created': '2020-03-27 19:31:23',
    # 'source': 'Reddit',
    # 'ticker': [],
    # 'publisher': 'detectivesher',
    # 'text': "My flights has been cancelled and airline is only offering me refund after 4-5 months and there is not guarantee. Isn't this illegal?\n\n\nI saw a consumer protection law stating that consumer should receive refund 60 days after a contract is cancelled, will this law be applied in my case ?",
    # 'title': 'Is it legal for Singapore airline to give refund only after 4-5 months after flight has been cancelled?',
    # 'score': 0,
    # 'url': 'https://www.reddit.com/r/singapore/comments/fpvd0o/is_it_legal_for_singapore_airline_to_give_refund/'},
    # {'datetime_created': '2020-10-14 16:40:54',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'jsyeo',
    # 'text': '',
    # 'title': 'Singapore Airlines fine-dining restaurant inside aircraft sells out',
    # 'score': 9,
    # 'url': 'https://www.businessinsider.com/singapore-airlines-fine-dining-restaurant-inside-aircraft-sells-out-2020-10'},
    # {'datetime_created': '2018-09-15 23:42:24',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'hughjazzmann',
    # 'text': '',
    # 'title': 'Singapore Airlines flight from Melbourne cancelled after pilot failed alcohol test',
    # 'score': 90,
    # 'url': 'http://www.channelnewsasia.com/news/singapore/singapore-airlines-pilot-failed-alcohol-test-melbourne-flight-10724922'},
    # {'datetime_created': '2018-06-13 12:52:36',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'throwawayburnerfuck',
    # 'text': '',
    # 'title': 'Taiwan protests move by Singapore Airlines, Scoot to name island as part of China',
    # 'score': 71,
    # 'url': 'https://www.straitstimes.com/asia/east-asia/taiwan-protests-move-by-singapore-airlines-scoot-to-name-island-as-part-of-china'},
    # {'datetime_created': '2020-04-03 00:04:17',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'ArmedSweeping',
    # 'text': '',
    # 'title': 'A MH 737 joins her sister, A SQ 707 and her mother, A MSA B707 (operated by singapore airlines) after the split. Unknown location, likely to be Paya Lebar airport singapore before 1981. CR:The Long and winding road on facebook',
    # 'score': 20,
    # 'url': 'https://i.redd.it/ox5oz1z9hfq41.jpg'},
    # {'datetime_created': '2020-08-09 13:47:47',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'justmewayne',
    # 'text': '',
    # 'title': 'Home | Singapore Airlines',
    # 'score': 22,
    # 'url': 'https://www.youtube.com/watch?v=GbH5QQwIlM4'},
    # {'datetime_created': '2018-04-30 15:42:15',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'janskyd',
    # 'text': '',
    # 'title': 'Singapore Airlines stops serving peanuts as snacks in all cabin classes',
    # 'score': 91,
    # 'url': 'https://www.straitstimes.com/singapore/singapore-airlines-stops-serving-peanuts-as-snacks-in-all-cabin-classes'},
    # {'datetime_created': '2019-06-28 20:45:18',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'fatenumber',
    # 'text': '',
    # 'title': 'Singapore Airlines, Malaysia Airlines ink deal to expand code-sharing',
    # 'score': 32,
    # 'url': 'https://www.straitstimes.com/singapore/transport/singapore-airlines-signs-mou-with-malaysia-airlines-for-strategic-partnership'},
    # {'datetime_created': '2019-03-29 22:43:35',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'avandleather',
    # 'text': '&#x200B;\n\nhttps://preview.redd.it/dutp3w8wl2p21.jpg?width=800&format=pjpg&auto=webp&s=fb83921017f3e33ada9d9e5df9fdad2cf92a52b8\n\nDisclaimer: SIA did not fully operate the Concorde aircraft, it was a joint operation by British Airways and SIA, with cabin crew alternating between the two airlines.\n\n&#x200B;\n\nLINK --> [https://www.heritageconcorde.com/singapore-airlines-concorde-operations](https://www.heritageconcorde.com/singapore-airlines-concorde-operations)\n\n&#x200B;\n\nDue to the fact that both British Airways and Air France were being denied landing rights at New York JFK, by the airports owners the Port Authority of New York. The two airlines needed to find new routes for their Concorde fleets. British Airways had another lucrative market apart from the North Atlantic routes; this was Asia, which included the British colony of Hong Kong, and the former colonies of Singapore and Australia.\n\n&#x200B;\n\nDuring Concorde’s route proving flights around the world, before the aircraft entered into service. A lot of effort when into the routes to the Australia and the Far East, which was in preparation for eventual passenger service on these routes using Concorde.\n\n&#x200B;\n\nBritish Airways and Singapore Airlines had originally announced their joint agreement for the thrice-weekly Concorde service between London and Singapore which was via Bahrain, on 26 October 1977. \xa0On 9 December 1977, British Airways and Singapore Airlines commenced a service between London and Singapore – Paya Lebar via a stop over in Bahrain, bringing the travel time to only 9 hours. So British Airways had now managed to extend their original Bahrain service (which was started in 1976 using Concorde G-BOAA) to Singapore.\n\n&#x200B;\n\nBritish Airways only used one aircraft on this route, the Concorde used was G-BOAD, which proudly displayed the Singapore Airways livery, but only on one side of the fuselage, as the other side was adorned with the British Airways Negus livery. This service set another first for Concorde; it was the first time that a Concorde had been flown in an airline livery other than that of British Airways or Air France. But the Singapore Airways livery gave them great free advert, and the route was always a combined BA /Singapore airlines route, with G-BOAD.\n\n&#x200B;\n\nOriginally British Airways had intended to fly supersonic through Indian airspace and some successful test proving flights had been completed earlier. However, by the time the service was due to commence, permission to overfly Indian Territory at supersonic speeds had been withdrawn by the Indian government. British Airways had to battle with the Indian government as they needed to gain this approval to fly supersonic over India, but in the end, Concorde was forced to avoid Indian airspace. This therefore added another 200 miles to Concorde’s route and 10 more minutes to its flight time, and therefore adding of course to increased fuel consumption during the flight. But it seems that the Indian government wasn’t objecting to the flight path of Concorde, they were using the situation to demand that in exchange for an approval of the flight path, Air India would gain further slots and 5th freedom rights at London Heathrow Airport.\n\nBut the service had only completed 3 flights before it was suspended owing to the Malaysian government withdrawing permission to overfly the Straits of Malacca. Concorde needed to fly at supersonic speeds over parts of its territory, this was finally resolved and the resumption of the service followed, Even though the service was not running the aircraft kept the Singapore Airlines livery during this time, giving them free adverts as the aircraft was utilised on other routes, including flights to the USA.\n\n&#x200B;\n\nThe difficulties with the Malaysians were due to them trying to use the Concorde operation to help them negotiate a 5th freedom right out of London Heathrow. The service was withdrawn on 13 December 1977 after only 3 return flights, because of these complaints from the Malaysian government about the supersonic boom over the Straits of Malacca, which is on the West coast of Malaysia. But in the summer of the same year, Malaysia Airlines plans of further capacity increase on the London route were denied in order to protect British Airways and Cathay Pacific, which caused a clash between the Malaysian and British governments. In addition to these difficult relations, Singapore Airlines was a tough Malaysian competitor.\n\n&#x200B;\n\nThis was finally resolved and the resumption of the service followed on the 24 January 1979, but it was not considered worth the trade as by then as British Airways had enough work for their aircraft on the route it was designed for the North Atlantic. So the service only lasted for 20 months before the service was withdrawn on the 1 November 1980, which was reportedly losing around £2 million a year, apart from the main factors was quoted, the west-bound load factors were very low.\n\nThe Singapore-Bahrain segment was also critical for payload as high temps regularly limited the Take-off weight. Although this was normally compensated for by the ability to cruise to Mach2 at both ends with no delays or speed restrictions straight from take-off. The route was London – Bahrain – Singapore and including the one hour stopover in Bahrain it took Concorde 9 hour’s approx to reach Singapore. The route was always a combined BA /Singapore airlines route with just one Concorde.\n\nThe operation to Bahrain was a mixture of sub and supersonic flight, whilst from Bahrain it was supersonic all the way. The cool moist air of the tropics between Bahrain and Singapore increased performance slightly, adding up to a 200 mile range increase with 75 pax.\n\nThe Flight deck crews were always British Airways with the cabin crew alternated by sector between British Airways and Singapore Airways. The London Heathrow-Singapore service was 3 times per week, and ran from January 1979 to November 1980.\n\nThe cabin crew was either completely Singapore Airlines or British Airways, and the two sets alternated the sectors. This meant that BA cabin crews turned up in Singapore and Singapore Airlines cabin crew turned up in London. Some BA flight deck crews were based in Singapore and operated only the Singapore – Bahrain – Singapore sectors. London based BA Flight crew operated the London – Bahrain – London sectors.\n\n&#x200B;\n\nTL;DR British Airways and SIA had an agreement to operate a London-Singapore Concorde flight thrice per week in 1977, made the Malaysian Government unhappy because of supersonic booms over Malaysia, barred the airliner from flying above Malaysian airspace which was already in the route, issue got resolved but flight service was closed because of losses.',
    # 'title': "Singapore Airlines once operated the Concorde, a supersonic aircraft capable of flying twice the speed of sound. But the service only operated for 3 years, and here's the story.",
    # 'score': 151,
    # 'url': 'https://www.reddit.com/r/singapore/comments/b6y4hq/singapore_airlines_once_operated_the_concorde_a/'},
    # {'datetime_created': '2019-05-09 10:26:30',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': '13peejay',
    # 'text': "**Such a scare for my friends' family that was on-board.**\n\n&#x200B;\n\n>A passenger on the flight, who did not want to identified, said that the pilot also announced that the aircraft had lost its steering capacity. “We were all set to land but the flight started to ascend… We were all scared. The flight made another attempt to land and did so with a jerk. We were asked to be prepare for a hard landing. The aircraft stopped in the middle of the runway and had to be towed away,” the passenger said.  \n  \n>  \n>SOURCE: [https://www.news18.com/news/auto/delhi-bound-singapore-airlines-makes-safe-landing-after-full-emergency-was-declared-2133657.html](https://www.news18.com/news/auto/delhi-bound-singapore-airlines-makes-safe-landing-after-full-emergency-was-declared-2133657.html)",
    # 'title': 'A “full emergency” was declared on board a Delhi-bound Singapore Airlines flight with 228 passengers',
    # 'score': 52,
    # 'url': 'https://www.reddit.com/r/singapore/comments/bmebls/a_full_emergency_was_declared_on_board_a/'},
    # {'datetime_created': '2018-11-20 19:41:20',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'your_comment_vocal',
    # 'text': "From Wikipedia: On 26 March 1991, Singapore Airlines Flight 117 was hijacked in flight by four Pakistani militants. The aircraft landed at Singapore. After their demands were not met, the hijackers threatened to begin killing hostages; before their deadline expired, commandos stormed the plane, killing the hijackers and freeing all hostages unhurt. This was the first and only hijacking involving a Singapore Airlines aircraft.\n\nYour military doesn't mess around!",
    # 'title': 'TIL about Singapore Airlines Flight 117 and just how badass the Singapore Armed Forces Commando Formation is.',
    # 'score': 38,
    # 'url': 'https://www.reddit.com/r/singapore/comments/9yrfej/til_about_singapore_airlines_flight_117_and_just/'},
    # {'datetime_created': '2018-05-18 08:19:05',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Varantain',
    # 'text': '',
    # 'title': 'SilkAir to be merged with Singapore Airlines after cabin revamp',
    # 'score': 63,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/silkair-to-be-merged-with-singapore-airlines-after-cabin-revamp-10245300'},
    # {'datetime_created': '2018-11-19 14:06:44',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Tropez92',
    # 'text': '',
    # 'title': 'Singapore Airlines flight forced to turn back to Changi after loss of cabin pressure',
    # 'score': 51,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/sia-flight-sq336-paris-turns-back-changi-cabin-pressure-10945254'},
    # {'datetime_created': '2019-02-07 10:46:46',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Captain_MacTavish',
    # 'text': '',
    # 'title': 'PSA to those who have these apps on your phones. Especially Expedia, Hotels.Com and Singapore Airlines.',
    # 'score': 51,
    # 'url': 'https://www.macrumors.com/2019/02/06/iphone-apps-screen-recordings-analytics/'},
    # {'datetime_created': '2020-03-03 09:20:19',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'HatchBeast',
    # 'text': '',
    # 'title': 'Despite saying they will (due to Covid-19) Singapore Airlines is still giving out hot towels and the reading materials are still in the back of the chairs',
    # 'score': 0,
    # 'url': 'https://i.redd.it/7cwruyv70dk41.jpg'},
    # {'datetime_created': '2020-10-26 22:10:07',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'Bcpjw',
    # 'text': '',
    # 'title': 'Grounded plane serves as restaurant to help Singapore Airlines stay aloft during Covid-19 pandemic',
    # 'score': 4,
    # 'url': 'https://youtu.be/IMkI4iDwaDk'},
    # {'datetime_created': '2019-12-13 23:47:58',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'silentscope90210',
    # 'text': '',
    # 'title': 'Does Singapore Airlines Have the Most Intense Cabin Crew Training in the World?',
    # 'score': 20,
    # 'url': 'https://www.youtube.com/watch?v=z8BnbjCPLFw'},
    # {'datetime_created': '2019-04-02 14:52:44',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'StandNTroll',
    # 'text': '',
    # 'title': 'Singapore Airlines grounds two Boeing 787-10 Dreamliner jets due to engine issues',
    # 'score': 33,
    # 'url': 'https://www.channelnewsasia.com/news/singapore/singapore-airlines-grounds-two-boeing-787-10-dreamliner-jets-due-11403920'},
    # {'datetime_created': '2017-01-31 20:52:06',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'bbycha',
    # 'text': 'Just curious about it and wanted to hear more opinions',
    # 'title': 'Is it worth it being a Singapore Airlines cabin crew?',
    # 'score': 61,
    # 'url': 'https://www.reddit.com/r/singapore/comments/5r8064/is_it_worth_it_being_a_singapore_airlines_cabin/'},
    # {'datetime_created': '2019-02-11 09:57:53',
    # 'source': 'Reddit',
    # 'ticker': ['Singapore Airlines Limited'],
    # 'publisher': 'jteruel',
    # 'text': '',
    # 'title': 'Pilots from Indian airline Vistara to fly for Singapore Airlines/Scoot',
    # 'score': 12,
    # 'url': 'http://www.flightsinasia.com/article/4308'},
    # {'datetime_created': '2022-03-24 13:11:35',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'unicornflai',
    # 'text': '',
    # 'title': 'Well, thank you for your wise words DBS. It gave me wisdom.',
    # 'score': 411,
    # 'url': 'https://i.redd.it/l9ahkb12m9p81.jpg'},
    # {'datetime_created': '2022-03-11 02:14:52',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'MicrotechAnalysis',
    # 'text': '',
    # 'title': 'DBS CEO Piyush Gupta gets S$13.58 million 2021 salary, up 48%',
    # 'score': 187,
    # 'url': 'https://mothership.sg/2022/03/dbs-ceo-salary-2021/'},
    # {'datetime_created': '2022-01-19 12:43:10',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'kimmyganny',
    # 'text': '',
    # 'title': "PSA It's here now guys, scammers targeting DBS the same way they targeted OCBC",
    # 'score': 900,
    # 'url': 'https://i.redd.it/9o9ux7inqkc81.jpg'},
    # {'datetime_created': '2022-01-20 09:32:56',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'Twrd4321',
    # 'text': '',
    # 'title': 'DBS sent me a letter to tell me I received a 10 cent bonus',
    # 'score': 1138,
    # 'url': 'https://i.redd.it/69etondmxqc81.jpg'},
    # {'datetime_created': '2022-02-12 16:05:23',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'skyscraper56',
    # 'text': '',
    # 'title': "DBS, POSB clients say accounts being drained even if they don't click on phishing links, or share passwords - The Independent Singapore News",
    # 'score': 83,
    # 'url': 'https://theindependent.sg/dbs-posb-clients-say-accounts-being-drained-even-if-they-dont-click-on-phishing-links-or-share-passwords/'},
    # {'datetime_created': '2022-02-07 20:44:30',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'HistorianSoviet',
    # 'text': '',
    # 'title': "MAS hits DBS with additional capital requirement after November's digital banking outage",
    # 'score': 67,
    # 'url': 'https://www.channelnewsasia.com/singapore/dbs-posb-digital-banking-outage-disruption-mas-2484216'},
    # {'datetime_created': '2022-02-14 20:39:14',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'Shaizay_Youn',
    # 'text': '',
    # 'title': "Singapore's megabank DBS ($500B in assets) to launch retail crypto trading by year-end",
    # 'score': 34,
    # 'url': 'https://www.coindesk.com/business/2022/02/14/dbs-plans-to-launch-retail-digital-assets-trading-desk-by-year-end/'},
    # {'datetime_created': '2022-03-18 19:24:00',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'lobangbecausenomoney',
    # 'text': '',
    # 'title': 'Former DBS manager given prohibition orders after deceiving clients into transferring S$490,000 to personal bank account',
    # 'score': 48,
    # 'url': 'https://www.channelnewsasia.com/singapore/former-dbs-wealth-management-manager-mas-prohibition-orders-cheating-clients-2573061'},
    # {'datetime_created': '2021-11-24 14:46:30',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'kushoon',
    # 'text': 'What an absolute clownfest this is, the outage has been going on for more than 24 hours with no end in sight and no formal communication on what is the ETA for resolution. There are so many businesses that run on a daily wage basis and the pressure has been growing with every passing minute plus individuals have bills to pay and stuff to buy for their small businesses, place orders using PayNow etc?\n\nLesson learned - not going to put all my eggs in 1 basket and make sure that DBS is not one of the baskets.\n\nEdit: Finally managed to login and PayNow at 8:30 pm 24th Nov - what a relief. Never felt this good parting with money.',
    # 'title': 'Absolute clownfest by DBS',
    # 'score': 721,
    # 'url': 'https://www.reddit.com/r/singapore/comments/r0yrq4/absolute_clownfest_by_dbs/'},
    # {'datetime_created': '2021-12-25 15:50:41',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'Singapuria007',
    # 'text': '',
    # 'title': 'I feel judged. A little passive aggressive DBS?',
    # 'score': 642,
    # 'url': 'https://i.imgur.com/6zvLX4D.jpg'},
    # {'datetime_created': '2022-02-18 12:26:05',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'MicrotechAnalysis',
    # 'text': '',
    # 'title': 'DBS commits additional $100m to philanthropic causes',
    # 'score': 26,
    # 'url': 'https://www.straitstimes.com/singapore/community/dbs-commits-additional-100m-to-philanthropic-causes'},
    # {'datetime_created': '2021-11-24 01:33:30',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'nonamecookie',
    # 'text': '',
    # 'title': 'Amongst the raging shitshow of DBS whole banking service outage lies a few hidden gems in comments section.',
    # 'score': 682,
    # 'url': 'https://www.reddit.com/gallery/r0ihdv'},
    # {'datetime_created': '2021-11-24 09:18:00',
    # 'source': 'Reddit',
    # 'ticker': ['DBS Group Holdings Ltd'],
    # 'publisher': 'Jammy_buttons2',
    # 'text': '',
    # 'title': 'DBS, POSB digital banking services fully restored after over 15 hours of disruption',
    # 'score': 97,
    # 'url': 'https://www.straitstimes.com/singapore/consumer/dbs-posb-digital-banking-services-restored-after-over-15-hours-of-disruption?utm_campaign=stfb&utm_medium=social&utm_source=facebook&fbclid=IwAR0cU4oTHe3NdwNjjLdgwcSQTMLqre4cWP8QijsxyfZP1YyVHIofAYQeez4'}
    # ]

    #DB
    myclient = pymongo.MongoClient("mongodb://localhost:27017/")
    mydb = myclient["textual_db"]
    mycol = mydb["reddit"]
    if mycol.count_documents({}) != 0:
            # If database contains other day's data, clear it
            mycol.delete_many({})    
    if sgx_list:
        mycol.insert_many(sgx_list)
